# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare a test file
        run: |
          mkdir -p build
          echo '<html><head><tille>Test</title></head><body><h1>Action test</h1></body></html>' > build/deploy-$(date +"%s").html

      - name: Deploy
        uses: ./
        id: deploy
        with:
          customer: quant
          project: github-actions
          token: ${{ secrets.QUANT_TOKEN }}
          dir: build
